optim: {
  type: 'AdamW',
  param: {
    lr: 0.001
  }
}

model: {
  type: 'attn_net',
  param: {
    in_dim: 1,
    out_dim: 3,
    embed_dim: 32,
    num_blocks: 2,
    num_heads: 2,
    ff_dim: 64,
  },
  log_dir: 'log/attn_net_single_block',
}

# VBH Grid.npy features:
# 0, 1, 2,  3,  4,  5,  6,    7,     8
# x, y, z, X1, X2, X3, Ye, TEMP, PRESS
# xyz: sperical alike
# x1x2x3: regular grid alike

dataset: {
  type: 'mantle_coord',
  param: {
    data_path: "data/earth_nopole_block.npy",
    curv_idx: [0,1,2],
    cart_idx: [3,4,5],
  },
  train_split: 0.8,
  valid_split: 0.2,
}

# dataloader: {
#   batch: 1048576,
# }


# reference batch numbers
# 2^16: 65536
# 2^17: 131072
# 2^18: 262144
# 2^19: 524288
# 2^20: 1048576
# 2^21: 2097152
# 2^22: 4194304
train: {
  max_epoch: 1500,
  batch: 1048576,
  # batch_log_step: step between batch number to save model
  batch_log_step: 9999999999,
  # log_step: step between epoch number to save model
  log_step: 10,
  resume: {
    ckpt: ckpt_499_000_2.96e-04,
  }
}