optim: {
  type: 'AdamW',
  param: {
    lr: 0.0001
  }
}

scheduler: {

}

model: {
  type: 'attn_net',
  param: {
    in_dim: 1,
    embed_dim: 128,
    num_blocks: 3,
    num_heads: 8,
    ff_dim: 512,
    out_dim: 3,
    pe_dim: 20,
  },
  log_dir: 'log/vls_mlp_attn',
}

# VBH Grid.npy features:
# 0, 1, 2,  3,  4,  5,  6,    7,     8
# x, y, z, X1, X2, X3, Ye, TEMP, PRESS
# xyz: sperical alike
# x1x2x3: regular grid alike

dataset: {
  type: 'vls_2022',
  param: {
    data_path: "data/bc80-45000-down.vts"
  },
  train_split: 0.95,
  valid_split: 0.05,
}

# dataloader: {
#   batch: 1048576,
# }

# reference batch numbers
# 2^16: 65536
# 2^17: 131072
# 2^18: 262144
# 2^19: 524288
# 2^20: 1048576
# 2^21: 2097152
# 2^22: 4194304
train: {
  max_epoch: 10000,
  batch: 524288,
  # batch_log_step: step between batch number to save model
  batch_log_step: 50,
  # log_step: step between epoch number to save model
  log_step: 50,
  resume: {
    ckpt: ckpt_0999_-001_8.29e-05,
  }
}
