optim: {
  type: 'AdamW',
  param: {
    lr: 0.001
  }
}

scheduler: {

}

model: {
  type: 'mlp_pe',
  param: {
    in_dim: 3,
    hidden_dims: [64, 64, 64, 64],
    out_dim: 3,
    pe_dim: 16,
  },
  log_dir: 'log/vls_mlp_lg',
}

# VBH Grid.npy features:
# 0, 1, 2,  3,  4,  5,  6,    7,     8
# x, y, z, X1, X2, X3, Ye, TEMP, PRESS
# xyz: sperical alike
# x1x2x3: regular grid alike

dataset: {
  type: 'vls_2022',
  param: {
    data_path: "data/bc80-45000-down.vts"
  },
  train_split: 0.9,
  valid_split: 0.1,
}

# dataloader: {
#   batch: 1048576,
# }

# reference batch numbers
# 2^16: 65536
# 2^17: 131072
# 2^18: 262144
# 2^19: 524288
# 2^20: 1048576
# 2^21: 2097152
# 2^22: 4194304
train: {
  max_epoch: 1000,
  batch: 524288,
  # batch_log_step: step between batch number to save model
  batch_log_step: 50,
  # log_step: step between epoch number to save model
  log_step: 50,
  resume: {
    ckpt: 0,
  }
}
